---
slug: :message_detail_view
depends:
  mikutter: '5.0'
  plugin:
  - gui
  - gtk3
  - intent
  - skin
  - twitter
version: '2.0'
author: toshi_a
name: ツイート詳細
description: 単一のツイートの詳細な内容を表示するタブを追加する
